version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - appnet

  backend:
    build: ./backend
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://admin:3N7wvVAt1MnTBHNx@cluster0.lf4cezd.mongodb.net/invoicedb?retryWrites=true&w=majority&appName=Cluster0
      - KEYCLOAK_REALM=mern-app
      - KEYCLOAK_AUTH_SERVER_URL=http://localhost:8080/
      - KEYCLOAK_CLIENT_ID=mern-frontend
      - SESSION_SECRET=your-secret-key
    ports:
      - "5000:5000"
    networks:
      - appnet

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev --db=dev-file
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - appnet

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  keycloak_data:
